# Generated by Django 4.0.2 on 2022-02-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='example',
            new_name='title',
        ),
        migrations.AddField(
            model_name='example',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
