# Generated by Django 4.0.2 on 2022-02-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_rename_example_example_title_example_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('filepath', models.FileField(null=True, upload_to='files', verbose_name='')),
            ],
        ),
    ]
