# Generated by Django 4.0.2 on 2022-02-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.AlterField(
            model_name='file',
            name='filepath',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
