# Generated by Django 4.0.2 on 2022-02-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_remove_file_name_alter_file_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
