# Generated by Django 4.0.2 on 2022-02-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_alter_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='tx_hash',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
